language: ruby
rvm:
 - 1.8.7
 - 1.9.3
 - 2.0.0
 - ruby-head
env:
 - "rake=0.9"
script: "bundle exec rspec -c"
notifications:
  email: false
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: ruby-head
